# Generated by Django 3.1.4 on 2021-05-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
