# Generated by Django 3.1.4 on 2021-05-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0011_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='blogApp.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=120),
        ),
    ]
